### ISSUE TITLE
Improve handling of SSH keys

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/nest#53]
SSH keys should be able to be updated by Nest Bot. However: Should they stay stored on Authentik, or should the `~/.ssh/authorized_keys` file be treated as the single source of truth?

**Comment by ajhalili2006** [comment]
In my opinion, I would suggest staying with `~/.ssh/authorized_keys` as source of truth for SSH pubkeys, since some may add them into their dotfiles' git tracking like mine (context: https://github.com/andreijiroh-dev/dotfiles/blob/main/.ssh/authorized_keys). Maybe we can ask the user in question if they have `~/.ssh/authorized_keys` on version control and ask them to commit changes first and let admins do `git pull` on their behalf?

**Comment by ajhalili2006** [comment]
Also to follow up, the user should be able to edit the SSH key while under review (remember the multi-line chaos when I submitted my application for Nest shell access) if they accidentally picked the wrong one and not after they got approved access.

**Comment by hello-smile6** [comment]
Can we make it clear that the one in authentik is strictly for getting access to nest when locked out and should not be used for day-to-day use, so people manage their own authorized_keys but put a key in authentik if they no longer control any of their keys on Nest?

**Comment by DaInfLoop** [comment]
> Can we make it clear that the one in authentik is strictly for getting access to nest when locked out and should not be used for day-to-day use, so people manage their own authorized_keys but put a key in authentik if they no longer control any of their keys on Nest?

Or users could use Cockpit when they don't control any of their keys, since you need your Authentik password for that (so it also just makes it easier to remember in case you for some reason need to access Authentik), and it's just easier to have to go:

1. Login to Cockpit
2. Add SSH key through terminal
3. Profit

Rather than:

1. Use Nest Bot to change SSH key
2. SSH in
3. Add new day-to-day key (as said in the comment)
4. Profit

**Comment by polypixeldev** [comment]
What if we just abandoned storing SSH keys in Authentik, and instead you would be able to use Nest Bot to edit your authorized_keys file from Slack? Something like this (drafted it in block kit builder):
![image](https://github.com/user-attachments/assets/870b5bd1-f635-4565-9b92-315acc36d098)

**Comment by DaInfLoop** [comment]
I feel like something similar to how Replit does it would be nicer where it shows the comment at the end aswell rather than the end of the key (unless that example just doesn't have a comment in the key)

![image](https://github.com/user-attachments/assets/fb444537-797b-46a4-800e-3a00a67a7696)

Edit: Something like this?
![image](https://github.com/user-attachments/assets/d73923d4-ca74-45ca-ab86-fb93b9efd079)

**Comment by polypixeldev** [comment]
Yeah that works

**Comment by hello-smile6** [comment]
Could we give users a way to directly edit their authorized_keys file, see a diff, and apply their changes if they feel comfortable?(There are lots of ways SSH keys could be formatted, including things like making a key run specific commands, so it'd be easy to accidentally do something destructive to a user key with a full GUI)

**Comment by polypixeldev** [comment]
Hmm, I'm not quite sure exactly what the issue is / how this would solve the issue? SSH keys entered through this UI would still have to go through the same validation that Nest Bot uses on signup right now.
